const librosDeLaBiblia = {
  antiguoTestamento: [
    { id: "genesis", nombre: "Génesis", abrev: "Gn" },
    { id: "exodo", nombre: "Éxodo", abrev: "Éx" },
    { id: "levitico", nombre: "Levítico", abrev: "Lv" },
    { id: "numeros", nombre: "Números", abrev: "Nm" },
    { id: "deuteronomio", nombre: "Deuteronomio", abrev: "Dt" },
    { id: "josue", nombre: "Josué", abrev: "Jos" },
    { id: "jueces", nombre: "Jueces", abrev: "Jue" },
    { id: "rut", nombre: "Rut", abrev: "Rt" },
    { id: "1_samuel", nombre: "1 Samuel", abrev: "1S" },
    { id: "2_samuel", nombre: "2 Samuel", abrev: "2S" },
    { id: "1_reyes", nombre: "1 Reyes", abrev: "1R" },
    { id: "2_reyes", nombre: "2 Reyes", abrev: "2R" },
    { id: "1_cronicas", nombre: "1 Crónicas", abrev: "1Cr" },
    { id: "2_cronicas", nombre: "2 Crónicas", abrev: "2Cr" },
    { id: "esdras", nombre: "Esdras", abrev: "Esd" },
    { id: "nehemias", nombre: "Nehemías", abrev: "Neh" },
    { id: "ester", nombre: "Ester", abrev: "Est" },
    { id: "job", nombre: "Job", abrev: "Job" },
    { id: "salmos", nombre: "Salmos", abrev: "Sal" },
    { id: "proverbios", nombre: "Proverbios", abrev: "Pr" },
    { id: "eclesiastes", nombre: "Eclesiastés", abrev: "Ec" },
    { id: "cantares", nombre: "Cantar de los Cantares", abrev: "Cnt" },
    { id: "isaias", nombre: "Isaías", abrev: "Is" },
    { id: "jeremias", nombre: "Jeremías", abrev: "Jer" },
    { id: "lamentaciones", nombre: "Lamentaciones", abrev: "Lm" },
    { id: "ezequiel", nombre: "Ezequiel", abrev: "Ez" },
    { id: "daniel", nombre: "Daniel", abrev: "Dn" },
    { id: "oseas", nombre: "Oseas", abrev: "Os" },
    { id: "joel", nombre: "Joel", abrev: "Jl" },
    { id: "amos", nombre: "Amós", abrev: "Am" },
    { id: "abdias", nombre: "Abdías", abrev: "Abd" },
    { id: "jonas", nombre: "Jonás", abrev: "Jon" },
    { id: "miqueas", nombre: "Miqueas", abrev: "Miq" },
    { id: "nahum", nombre: "Nahúm", abrev: "Nah" },
    { id: "habacuc", nombre: "Habacuc", abrev: "Hab" },
    { id: "sofonias", nombre: "Sofonías", abrev: "Sof" },
    { id: "hageo", nombre: "Hageo", abrev: "Hag" },
    { id: "zacarias", nombre: "Zacarías", abrev: "Zac" },
    { id: "malaquias", nombre: "Malaquías", abrev: "Mal" },
  ],
  nuevoTestamento: [
    { id: "mateo", nombre: "Mateo", abrev: "Mt" },
    { id: "marcos", nombre: "Marcos", abrev: "Mr" },
    { id: "lucas", nombre: "Lucas", abrev: "Lc" },
    { id: "juan", nombre: "Juan", abrev: "Jn" },
    { id: "hechos", nombre: "Hechos", abrev: "Hch" },
    { id: "romanos", nombre: "Romanos", abrev: "Ro" },
    { id: "1_corintios", nombre: "1 Corintios", abrev: "1Co" },
    { id: "2_corintios", nombre: "2 Corintios", abrev: "2Co" },
    { id: "galatas", nombre: "Gálatas", abrev: "Gá" },
    { id: "efesios", nombre: "Efesios", abrev: "Ef" },
    { id: "filipenses", nombre: "Filipenses", abrev: "Fil" },
    { id: "colosenses", nombre: "Colosenses", abrev: "Col" },
    { id: "1_tesalonicenses", nombre: "1 Tesalonicenses", abrev: "1Ts" },
    { id: "2_tesalonicenses", nombre: "2 Tesalonicenses", abrev: "2Ts" },
    { id: "1_timoteo", nombre: "1 Timoteo", abrev: "1Ti" },
    { id: "2_timoteo", nombre: "2 Timoteo", abrev: "2Ti" },
    { id: "tito", nombre: "Tito", abrev: "Tit" },
    { id: "filemon", nombre: "Filemón", abrev: "Flm" },
    { id: "hebreos", nombre: "Hebreos", abrev: "He" },
    { id: "santiago", nombre: "Santiago", abrev: "Stg" },
    { id: "1_pedro", nombre: "1 Pedro", abrev: "1P" },
    { id: "2_pedro", nombre: "2 Pedro", abrev: "2P" },
    { id: "1_juan", nombre: "1 Juan", abrev: "1Jn" },
    { id: "2_juan", nombre: "2 Juan", abrev: "2Jn" },
    { id: "3_juan", nombre: "3 Juan", abrev: "3Jn" },
    { id: "judas", nombre: "Judas", abrev: "Jud" },
    { id: "apocalipsis", nombre: "Apocalipsis", abrev: "Ap" },
  ],
};

export default librosDeLaBiblia;
